name = "YoungTableaux"
uuid = "b7062236-b0aa-4473-bf76-66f344053691"
authors = ["Simeon David Schaub <schaub@mit.edu> and contributors"]
version = "1.0.0-DEV"

[deps]
HypertextLiteral = "ac1192a8-f4b3-4bfe-ba22-af5b92cd3ab2"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
